version: '3.8'

services:
  postgres:
    container_name: 'postgres_db'
    restart: always
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=QuizMgtDB'
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
